# Generated by Django 5.1.5 on 2025-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='genre',
            field=models.CharField(default='khác', max_length=50),
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(default='ongoing', max_length=50),
        ),
    ]
